# festivals-server configuration file v1.0
# TOML 1.0.0-rc.2+

[service]
bind-address = "localhost"
bind-host = "localhost"
port = 10439
key = "TEST_API_KEY_001"
read-only = false

[tls]
festivaslapp-root-ca = "/usr/local/festivals-server/ca.crt"
cert = "/usr/local/festivals-server/server.crt"
key = "/usr/local/festivals-server/server.key"

[database]
host = "localhost"
port = 3306
username = "festivals.api.writer"
password = "we4711"
database-name = "festivals_api_database"

[heartbeat]
endpoint = "localhost"
interval = 6

[authentication]
api-keys = ["TEST_API_KEY_001", "TEST_API_KEY_002", "TEST_API_KEY_003"]
admin-keys = ["TEST_API_KEY_001"]