# festivals-server configuration file v1.0

[service]
read-only = false
port = 10439

[database]
host = "192.168.8.206"
port = 3306
username = "festivals.api.writer"
password = "we4711"
database-name = "festivals_api_database"