# festivals-server configuration file v1.0
# TOML 1.0.0-rc.2+

[service]
read-only = false
bind-address = "localhost"
port = 10439

[database]
host = "localhost"
port = 3306
username = "festivals.api.writer"
password = "we4711"
database-name = "festivals_api_database"

[authentication]
heartbeat = "localhost"
api-keys = ["TEST_API_KEY_001", "TEST_API_KEY_002", "TEST_API_KEY_003"]